#!/usr/bin/env python

from opster import command

a = 0

@command(usage="%name [-p|--pptx] [-x|--xslx] [-w|--wrdx] [-a|--abstract]")
def main(pptx=('p', False, 'should we generate pptx related code'),
         xslx=('x', False, 'should we generate xslx related code'),
         wrdx=('w', False, 'should we generate wrdx related code'),
         abstract=('a', False, 'should we generate abstract ifaces')):
    """
    Code generation tool. Run without params to regenerate all the code
    """
    global a
    a = 42

if __name__ == '__main__':
    main()
    assert a == 42, "WTF???"
